export const constants = {
  AWS_LAMBDA_GENERATE_ACCESS_TOKEN: process.env.AWS_LAMBDA_GENERATE_ACCESS_TOKEN,

  AWS_API_VERSION: process.env.AWS_API_VERSION,
  AWS_ACCESS_KEY: process.env.AWS_AUTH_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_AUTH_SECRET_KEY,
  AWS_REGION: process.env.AWS_REGION_CODE,
  AES_SECRET_CIPHER_TOKEN: process.env.AES_SECRET_CIPHER_TOKEN,
  AES_SECRET_CIPHER_PASS_VNL: process.env.AES_SECRET_CIPHER_PASS_VNL,
  MAXIMUM_USER_BLOCKING_MINUTES: process.env.MAXIMUM_USER_BLOCKING_MINUTES,
  ACCESS_TOKEN_EXPIRATION_TIME: process.env.ACCESS_TOKEN_EXPIRATION_TIME,
  DB_HOSTNAME: process.env.DB_HOSTNAME,
  DB_NAME: process.env.DB_NAME,
  DB_USER: process.env.DB_USER,
  DB_PASSWORD: process.env.DB_PASSWORD,
  COLLECTION_NAME_USERS: process.env.COLLECTION_NAME_USERS,
  COLLECTION_NAME_HASHES: process.env.COLLECTION_NAME_HASHES,
  COLLECTION_NAME_TOKEN: process.env.COLLECTION_NAME_TOKEN
}